# Generated by Django 6.0.1 on 2026-02-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_cliente_cpf_cnpj_cliente_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
